name: Remote-Call

on:
  workflow_dispatch:
    # inputs:
    #   ref:
    #     required: true
    #     type: string

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: post
        run: |
          gh api --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          repos/sammnnz/geompy/actions/workflows/tests-os-py.yml/dispatches -f "ref=develop" -f "inputs[os]=ubuntu-latest" -f "inputs[py]=3.8"
        
