name: Remote-Call

on:
  workflow_dispatch:
    # inputs:
    #   ref:
    #     required: true
    #     type: string

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: post
        run: |
          gh api --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          repos/sammnnz/geompy/actions/workflows/tests-mac.yml/dispatches -f "ref=_te-2_call_dispatch" -f "inputs[ref]=_te-2_call_dispatch" -f "inputs[os]=windows-latest" -f "inputs[py]=3.9"
        
