name: Remote-Call

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string
        default: 'develop'
      workflow_id:
        required: true
        type: string
        default: 'tests-os-py.yml'
      arg-name-1:
        required: false
        type: string
      arg-value-1:
        required: false
        type: string
      arg-name-2:
        required: false
        type: string
      arg-value-2:
        required: false
        type: string
      arg-name-3:
        required: false
        type: string
      arg-value-3:
        required: false
        type: string
      arg-name-4:
        required: false
        type: string
      arg-value-4:
        required: false
        type: string

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - id: parse-arg
        run: |
          ARGS=""
          for (( i=1; i <= 6; i++ )); do
            if [ ${{inputs.arg-name-$i}} == '' ]; then
              continue
            fi
            # echo "${{inputs.arg-name-$i}}"
            ARGS+=" -f inputs[${{inputs.arg-name-$i}}]=${{inputs.arg-value-$i}}"
          done
          echo "$ARGS" >> $GITHUB_OUTPUT
        shell: bash

    outputs:
      lint: ${{ steps.parse-arg.outputs.value }}

  # call:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: post
  #       run: |
  #         gh api --method POST \
  #         -H "Accept: application/vnd.github+json" \
  #         -H "X-GitHub-Api-Version: 2022-11-28" \
  #         repos/sammnnz/geompy/actions/workflows/${{inputs.workflow_id}}/dispatches -f "ref=${{inputs.ref}}" -f "inputs[os]=ubuntu-latest" -f "inputs[py]=3.8"
  #       env:
  #         GH_TOKEN: ${{ secrets.REMOTE_CALL_SECRET }}
        
