name: Tests-single

on:
   workflow_dispatch:
     inputs:
       ref:
         required: true
         type: string
         default: 'develop'
       os:
         required: true
         type: choice
         default: 'windows-latest'
         options:
         # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#standard-github-hosted-runners-for-public-repositories
         - ubuntu-latest
         - ubuntu-24.04
         - ubuntu-22.04
         - ubuntu-20.04
         - windows-latest
         - windows-2025
         - windows-2022
         - windows-2019
         - ubuntu-24.04-arm
         - ubuntu-22.04-arm
         - macos-13
         - macos-latest
         - macos-14
         - macos-15
       py:
         required: true
         type: choice
         default: '3.9'
         options:
         - '3.7'
         - '3.8'
         - '3.9'
         - '3.10'
       lint:
         required: false
         type: string
         default: ''
       typecheck:
         required: false
         type: string
         default: ''

jobs:
  # tests-call-main:
  #    if: ${{inputs.ref}} == 'main'
  #    uses: sammnnz/geompy/.github/workflows/tests.yml@main
  #    with:
  #      os: ${{inputs.os}}
  #      py: ${{inputs.py}}
  #      lint: ${{inputs.lint}}
  #      typecheck: ${{inputs.typecheck}}

  tests-call-develop:
     if: ${{inputs.ref}} == 'develop'
     uses: sammnnz/geompy/.github/workflows/tests.yml@develop
     with:
       ref: ${{inputs.ref}}
       os: ${{inputs.os}}
       py: ${{inputs.py}}
       lint: ${{inputs.lint}}
       typecheck: ${{inputs.typecheck}}
