name: Tests-ub-win

on:
   workflow_dispatch:
     inputs:
       ref:
         required: true
         type: string
         default: 'develop'

jobs:
  tests-call-te:
     if: ${{ inputs.ref }} == 'te-1_workflow_call'
     uses: sammnnz/geompy/.github/workflows/tests-ub-win.yml@te-1_workflow_call
     with:
        ref: ${{inputs.ref}}
